name: GitHub Actions Demo
run-name: ${{ github.event.head_commit.message }} (${{ github.event.base_ref }})
on:
  push:
    tags:
      - current-release
      - current-release-frontend
      - current-release-return-portal
      - pre-release
      - pre-release-frontend
      - pre-release-return-portal
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ toJSON(github) }}"

      - name: Build return-portal
        if: contains('frontend', github.ref) == 'false'
        run: echo "Build return-portal ${{ github.ref }}."

      - name: Build application
        if: contains('return-portal', github.ref) == 'false'
        run: echo "Build application ${{ github.ref }}."

#      - name: Build return-portal
#        if: github.ref != 'refs/tags/current-release-frontend' || github.ref == 'refs/tags/pre-release-frontend'
#        run: echo "Build return-portal ${{ github.ref }}."
#
#      - name: Build application
#        if: github.ref != 'refs/tags/current-release-return-portal' || github.ref == 'refs/tags/pre-release-return-portal'
#        run: echo "Build application ${{ github.ref }}."




#      - name: Build return-portal (Pre-release)
#        if: ${{ github.ref == 'refs/tags/pre-release' || github.ref == 'refs/tags/pre-release-return-portal' }}
#        run: echo " Build return-portal ${{ github.ref }}."
#
#      - name: Build application (Pre-release)
#        if: ${{ github.ref == 'refs/tags/pre-release' || github.ref == 'refs/tags/pre-release-frontend' }}
#        run: echo " Build app ${{ github.ref }}."
#
#      - name: Build return-portal (Pre-release)
#        if: ${{ github.ref == 'refs/tags/pre-release' || github.ref == 'refs/tags/pre-release-return-portal' }}
#        run: echo " Build return-portal ${{ github.ref }}."
#
#      - name: Build application (Release)
#        if: ${{ github.ref == 'refs/tags/current-release' || github.ref == 'refs/tags/current-release-frontend' }}
#        run: echo " Build app ${{ github.ref }}."

